#!/usr/bin/env bash

if git diff --cached --name-only | grep -q 'R/prior_default_settings.R'; then
  echo "Rebuilding default_prior_settings.rda..."
  Rscript data_generation/make_prior_default_settings.R || {
    echo "make_prior_default_settings.R failed. Commit aborted."
    exit 1
  }
else
  echo "default_prior_settings.rda did not need to be rebuilt"
fi
